UAutonomaA/Controllers/AdmisionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAutonomaA.Models;
using UAutonomaA.DAL;

namespace UAutonomaA.Controllers
{
    public class AdmisionesController : Controller
    {
        private UAutonomaContext db = new UAutonomaContext();
        //private ProgramaDbContext dbProgramas = new ProgramaDbContext();
        private Inscripcion inscripcion = new Inscripcion();
        //private EstudianteDBContext dbEstudiante = new EstudianteDBContext();

        // GET: Admisiones
        public ActionResult Index()
        {
            try
            {
                ViewBag.Message = TempData["Messages"].ToString();
            }
            catch (Exception)
            {
                ViewBag.Message = string.Empty;
               
            }
            return View();
        }

        // GET: Programas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Programas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,nombre_programa,sede")] Inscripcion inscripcion)
        {
            if (ModelState.IsValid)
            {
                db.Inscripcions.Add(inscripcion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inscripcion);
        }

        
        public ActionResult Registro()
        {
            try
            {
                ViewBag.Error = TempData["Error"].ToString();
            }
            catch (Exception)
            {
                ViewBag.Error = string.Empty;
            }
            /* @Html.EnumDropDownListFor(model => model.Tipo_aspirante, new { htmlAttributes = new { @class = "form-control" } }) */
            if ( this.db.Programas.Count() < 1)
            {
                TempData["Messages"] = "Error, aun no hay programas registrados por el adminsitrador";
                return RedirectToAction("Index");
            }
            else
            {
               
                ViewBag.Programas = new SelectList(this.db.Programas.ToList(), "ID", "Nombre");
                ViewBag.Tipo_aspirantes = new SelectList(Enum.GetValues(typeof(Tipo_Aspirante)));
                ViewBag.Modalidades = new SelectList(Enum.GetValues(typeof(Modalidad)));
                ViewBag.Sedes = new SelectList(Enum.GetValues(typeof(Sede)));
                ViewBag.Periodos = new SelectList(new List<string> { "20191", "20192", "20201", "20202" }); 
            }
            this.inscripcion.Programa = new Programa();
            this.inscripcion.Estudiante = new Estudiante();
            return View();
        }

        public ActionResult Personal()
        {
            try
            {
                if ((bool)TempData["registro"])
                {
                    return View();
                }
                else
                {
                    throw new Exception();
                }
            }
            catch (Exception)
            {
                TempData["Messages"] = "Error, proceso de inscripcion sin iniciar";
                return RedirectToAction("Index");               
            }          
            
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Personal([Bind(Include = "ID,Tipo_doc,Numero_doc,Fecha_exp,Pais_exp,Dpto_exp,Ciudad_exp,Sexo,Primer_nombre,Segundo_nombre,Primer_apellido,Segundo_apellido,Fecha_nacimiento,Pais,Departamento,Ciudad,Telefono,Celular,Correo,Grupo_Sanguineo,Estado_Civil")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                this.db.Estudiantes.Add(estudiante);
                this.db.SaveChanges();
                this.inscripcion = (Inscripcion)TempData["Inscripcion"];
                this.inscripcion.EstudianteID = estudiante.ID;
                this.inscripcion.Estado = "Inscrito";
                this.db.Inscripcions.Add(this.inscripcion);
                this.db.SaveChanges();
                TempData["Messages"] = "Registro realizado con exito #registro: " + this.inscripcion.ID ;
                return RedirectToAction("Index");
            }

            return View(estudiante);
        }

        [HttpPost]      
        public ActionResult Registro(string  tipo_aspirante, string modalidad, string sede, string periodo, string programa)
        {
            if( string.IsNullOrEmpty(tipo_aspirante) || string.IsNullOrEmpty(modalidad) ||  string.IsNullOrEmpty(sede) || string.IsNullOrEmpty(periodo) || string.IsNullOrEmpty(programa))
            {
                //ModelState.AddModelError("", "Debes completar los campos requeridos");
                TempData["Error"] = "Te hacen falta Atributos Requeridos";
                return RedirectToAction("Registro");
            }
            
            this.inscripcion.Periodo = periodo;            
            this.inscripcion.ProgramaID = int.Parse(programa);
            Tipo_Aspirante tipo;
            if(Enum.TryParse(tipo_aspirante, out tipo)){
                this.inscripcion.Tipo_aspirante = tipo;
            }
            TempData["Inscripcion"] = inscripcion;
            TempData["registro"] = true;
            return RedirectToAction("Personal");
        }

        public Boolean RegistrarInscripcion(Estudiante estudiante, int programaId, string periodo, string estado)
        {      
            db.Estudiantes.Add(estudiante);         
            int idEst = db.SaveChanges();
            Inscripcion inscripcion = new Inscripcion();           
            inscripcion.Periodo = periodo;            
            db.Inscripcions.Add(inscripcion);
            db.SaveChanges();
            return true;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UAutonomaA/Views/Admisiones/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    var data = ViewBag.Message;
}

<h3 class="alert-danger"> @data</h3>

<div class="table-hover">
    <div class="row">
        <div class="col-md-6">
            <h2>Admisiones</h2>
            <p>
                Para iniciar el proceso de Registro haz en el boton Iniciar
            </p>
            @Html.ActionLink("Iniciar", "Registro", "Admisiones", new { area = "" }, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

UAutonomaA/Views/Admisiones/Personal.cshtml
@model UAutonomaA.Models.Estudiante


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    <h4>  @Html.Label("Informacion Personal", htmlAttributes: new { @class = "text-info" })</h4>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Tipo_doc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Tipo_doc, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Tipo_doc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Numero_doc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Numero_doc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Numero_doc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fecha_exp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fecha_exp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fecha_exp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pais_exp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pais_exp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pais_exp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dpto_exp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Dpto_exp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Dpto_exp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ciudad_exp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ciudad_exp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ciudad_exp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Sexo, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Primer_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Primer_nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Primer_nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Segundo_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Segundo_nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Segundo_nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Primer_apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Primer_apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Primer_apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Segundo_apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Segundo_apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Segundo_apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fecha_nacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fecha_nacimiento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fecha_nacimiento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Departamento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Grupo_Sanguineo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Grupo_Sanguineo, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Grupo_Sanguineo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado_Civil, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Estado_Civil, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Estado_Civil, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Registrar" class="btn btn-info" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UAutonomaA/Views/Admisiones/Registro.cshtml
@using UAutonomaA.Models;


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
      
        var data = ViewBag.Error;
    

  

<div class="form-inline">
    <hr />
    <h4>  @Html.Label("Informacion de Inscripcion", htmlAttributes: new { @class = "text-info" })</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-12">
            @Html.Label("Tipo Aspirante*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">
                <div class="col-md-12">
                    <div class="col-md-3">
                        <label>
                            @Html.RadioButton("tipo_aspirante", "Nuevo")
                            @Html.ValidationMessage("tipo_aspirante", "", new { @class = "text-danger" })
                            Nuevo
                        </label>
                    </div>
                    <div class="col-md-3">
                        <label>
                            @Html.RadioButton("tipo_aspirante", "Reingreso")
                            @Html.ValidationMessage("tipo_aspirante", "", new { @class = "text-danger" })
                            Reingreso
                        </label>
                    </div>
                    <div class="col-md-3">
                        <label>
                            @Html.RadioButton("tipo_aspirante", "Transferencia Interna")
                            @Html.ValidationMessage("tipo_aspirante", "", new { @class = "text-danger" })
                            Transferencia Interna
                        </label>
                    </div>
                    <div class="col-md-3">
                        <label>
                            @Html.RadioButton("tipo_aspirante", "Transferencia Externa")
                            @Html.ValidationMessage("tipo_aspirante", "", new { @class = "text-danger" })
                            Transferencia Externa
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            @Html.Label("Modalidad*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">
                @Html.DropDownList("modalidad", ViewBag.Modalidades as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("modalidad", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            @Html.Label("Programa*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">
                @Html.DropDownList("programa", ViewBag.Programas as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("programa", "", new { @class = "text-danger" })

            </div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            @Html.Label("Sede*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">
                @Html.DropDownList("sede", ViewBag.Sedes as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("sede", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            @Html.Label("Periodo*", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-group">
                @Html.DropDownList("periodo", ViewBag.Periodos as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("periodo", "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <hr />



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Siguiente" class="btn btn-info" />
        </div>
    </div>
    <h3 class="alert-danger"> @data</h3>

</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}