UAutonomaA/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAutonomaA.DAL;
using UAutonomaA.Models;

namespace UAutonomaA.Controllers
{
    public class AdminController : Controller
    {
        private UAutonomaContext db = new UAutonomaContext();

        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.Message = "Pagina de Administracion..";
            return View();
        }

        public ActionResult Aspirantes()
        {
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Login()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Login(string user, string pass)
        {
            try
            {
                if(user == "" || pass == "")
                {
                    ModelState.AddModelError("", "Usuario y Password son requeridos");
                    return View();
                }
                if(user == "admin" && pass == "admin")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Pista: admin admin");
                    return View();
                }
                
            }
            catch (Exception)
            {
                return View();
            }
        }

        public ActionResult Listado()
        {
            List<Inscripcion> inscripcions = db.Inscripcions.ToList();
            foreach (var item in inscripcions)
            {
                item.Programa = db.Programas.Find(item.ProgramaID);
                item.Estudiante = db.Estudiantes.Find(item.EstudianteID);
            }
            return View(inscripcions);
        }
    }
}

UAutonomaA/Controllers/ProgramasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UAutonomaA.Models;
using UAutonomaA.DAL;

namespace UAutonomaA.Controllers
{
    public class ProgramasController : Controller
    {
        private UAutonomaContext db = new UAutonomaContext();

        // GET: Programas
        public ActionResult Index()
        {
            return View(db.Programas.ToList());
        }

        // GET: Programas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programa programa = db.Programas.Find(id);
            if (programa == null)
            {
                return HttpNotFound();
            }
            return View(programa);
        }

        // GET: Programas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Programas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Sede,Modalidad")] Programa programa)
        {
            if (ModelState.IsValid)
            {
                db.Programas.Add(programa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(programa);
        }

        // GET: Programas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programa programa = db.Programas.Find(id);
            if (programa == null)
            {
                return HttpNotFound();
            }
            return View(programa);
        }

        // POST: Programas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Sede,Modalidad")] Programa programa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(programa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(programa);
        }

        // GET: Programas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Programa programa = db.Programas.Find(id);
            if (programa == null)
            {
                return HttpNotFound();
            }
            return View(programa);
        }

        // POST: Programas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Programa programa = db.Programas.Find(id);
            db.Programas.Remove(programa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UAutonomaA/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Inicio Administrador";
}

<h2>Bienvenido Administrador!</h2>

<div class="table-hover">
    <div class="row">
        <div class="col-md-6">        
            @Html.ActionLink("Gestión de Programas", "Index", "Programas", new { area = "" }, new { @class = "btn btn-primary" })
        </div>
    </div>
    <div class="row">
        </br>
    </div>
    <div class="row">
        <div class="col-md-6">
            @Html.ActionLink("Gestión de Inscripciones", "Listado", "Admin", new { area = "" }, new { @class = "btn btn-success" })
        </div>
    </div>
</div>

UAutonomaA/Views/Admin/Listado.cshtml
@using UAutonomaA.Models;
@model IEnumerable<UAutonomaA.Models.Inscripcion>

<h3>Aspirantes Inscritos</h3>
<table class="table-responsive table-bordered table-condensed table-hover">
    <tr>
        <th>
            @Html.DisplayName("Estado")
        </th>
        <th>
            @Html.DisplayName("Sede")
        </th>
        <th>
            @Html.DisplayName("Programa Academico")
        </th>
        <th>
            @Html.DisplayName("Periodo Academico")
        </th>
        <th>
            @Html.DisplayName("Tipo de Documento")
        </th>
        <th>
            @Html.DisplayName("Numero de Documento")
        </th>
        <th>
            @Html.DisplayName("Nombres")
        </th>
        <th>
            @Html.DisplayName("Apellidos")
        </th>
        <th>
            @Html.DisplayName("Numero de Telefono")
        </th>
        <th>
            @Html.DisplayName("Numero de Celular")
        </th>
        <th>
            @Html.DisplayName("Correo")
        </th>       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Programa.Sede)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Programa.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Periodo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante.Tipo_doc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante.Numero_doc)
        </td>
        <td>
            @Html.Label(item.Estudiante.Primer_nombre + " " + item.Estudiante.Segundo_nombre)
        </td>
        <td>
            @Html.Label(item.Estudiante.Primer_apellido + " " + item.Estudiante.Segundo_apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante.Celular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante.Correo)
        </td>
    </tr>
}

</table>

UAutonomaA/Views/Admin/Login.cshtml
@{
    ViewBag.Title = "Create";
}

<h3>Login Administracion</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Usuario", htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.Editor("user", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("user", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("pass", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("pass", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}